
package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Benificiaire generated by hbm2java
 */
public class Benificiaire  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String prenom;
     private String fonction;
     private Set cycloBenificiaires = new HashSet(0);

    public Benificiaire() {
    }

	
    public Benificiaire(String nom, String prenom, String fonction) {
        this.nom = nom;
        this.prenom = prenom;
        this.fonction = fonction;
    }
    public Benificiaire(String nom, String prenom, String fonction, Set cycloBenificiaires) {
       this.nom = nom;
       this.prenom = prenom;
       this.fonction = fonction;
       this.cycloBenificiaires = cycloBenificiaires;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public Set getCycloBenificiaires() {
        return this.cycloBenificiaires;
    }
    
    public void setCycloBenificiaires(Set cycloBenificiaires) {
        this.cycloBenificiaires = cycloBenificiaires;
    }




}


