package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1



/**
 * BoiteEtat generated by hbm2java
 */
public class BoiteEtat  implements java.io.Serializable {


     private Integer id;
     private Boitelettres boitelettres;
     private Etat etat;

    public BoiteEtat() {
    }

    public BoiteEtat(Boitelettres boitelettres, Etat etat) {
       this.boitelettres = boitelettres;
       this.etat = etat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Boitelettres getBoitelettres() {
        return this.boitelettres;
    }
    
    public void setBoitelettres(Boitelettres boitelettres) {
        this.boitelettres = boitelettres;
    }
    public Etat getEtat() {
        return this.etat;
    }
    
    public void setEtat(Etat etat) {
        this.etat = etat;
    }




}


