package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Boitelettres generated by hbm2java
 */
public class Boitelettres  implements java.io.Serializable {


     private Integer id;
     private Tournee tournee;
     private String adresse;
     private String lettreDistinctive;
     private String type;
     private int cp;
     private Set boiteEtats = new HashSet(0);

    public Boitelettres() {
    }

	
    public Boitelettres(Tournee tournee, String adresse, String lettreDistinctive, String type, int cp) {
        this.tournee = tournee;
        this.adresse = adresse;
        this.lettreDistinctive = lettreDistinctive;
        this.type = type;
        this.cp = cp;
    }
    public Boitelettres(Tournee tournee, String adresse, String lettreDistinctive, String type, int cp, Set boiteEtats) {
       this.tournee = tournee;
       this.adresse = adresse;
       this.lettreDistinctive = lettreDistinctive;
       this.type = type;
       this.cp = cp;
       this.boiteEtats = boiteEtats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tournee getTournee() {
        return this.tournee;
    }
    
    public void setTournee(Tournee tournee) {
        this.tournee = tournee;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getLettreDistinctive() {
        return this.lettreDistinctive;
    }
    
    public void setLettreDistinctive(String lettreDistinctive) {
        this.lettreDistinctive = lettreDistinctive;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public Set getBoiteEtats() {
        return this.boiteEtats;
    }
    
    public void setBoiteEtats(Set boiteEtats) {
        this.boiteEtats = boiteEtats;
    }




}


