package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CycloFacteur generated by hbm2java
 */
public class CycloFacteur  implements java.io.Serializable {


     private Integer id;
     private Cyclo cyclo;
     private Facteur facteur;
     private Date date;

    public CycloFacteur() {
    }

    public CycloFacteur(Cyclo cyclo, Facteur facteur, Date date) {
       this.cyclo = cyclo;
       this.facteur = facteur;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cyclo getCyclo() {
        return this.cyclo;
    }
    
    public void setCyclo(Cyclo cyclo) {
        this.cyclo = cyclo;
    }
    public Facteur getFacteur() {
        return this.facteur;
    }
    
    public void setFacteur(Facteur facteur) {
        this.facteur = facteur;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


