package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CycloBenificiaire generated by hbm2java
 */
public class CycloBenificiaire  implements java.io.Serializable {


     private Integer id;
     private Benificiaire benificiaire;
     private Cyclo cyclo;
     private Date date;

    public CycloBenificiaire() {
    }

    public CycloBenificiaire(Benificiaire benificiaire, Cyclo cyclo, Date date) {
       this.benificiaire = benificiaire;
       this.cyclo = cyclo;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Benificiaire getBenificiaire() {
        return this.benificiaire;
    }
    
    public void setBenificiaire(Benificiaire benificiaire) {
        this.benificiaire = benificiaire;
    }
    public Cyclo getCyclo() {
        return this.cyclo;
    }
    
    public void setCyclo(Cyclo cyclo) {
        this.cyclo = cyclo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


