package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cyclo generated by hbm2java
 */
public class Cyclo  implements java.io.Serializable {


     private Integer id;
     private Tournee tournee;
     private int matricule;
     private Date dateCarteGrise;
     private Date datePu;
     private int reference;
     private Set cycloFacteurs = new HashSet(0);
     private Set cycloBenificiaires = new HashSet(0);

    public Cyclo() {
    }

	
    public Cyclo(Tournee tournee, int matricule, Date dateCarteGrise, Date datePu, int reference) {
        this.tournee = tournee;
        this.matricule = matricule;
        this.dateCarteGrise = dateCarteGrise;
        this.datePu = datePu;
        this.reference = reference;
    }
    public Cyclo(Tournee tournee, int matricule, Date dateCarteGrise, Date datePu, int reference, Set cycloFacteurs, Set cycloBenificiaires) {
       this.tournee = tournee;
       this.matricule = matricule;
       this.dateCarteGrise = dateCarteGrise;
       this.datePu = datePu;
       this.reference = reference;
       this.cycloFacteurs = cycloFacteurs;
       this.cycloBenificiaires = cycloBenificiaires;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tournee getTournee() {
        return this.tournee;
    }
    
    public void setTournee(Tournee tournee) {
        this.tournee = tournee;
    }
    public int getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(int matricule) {
        this.matricule = matricule;
    }
    public Date getDateCarteGrise() {
        return this.dateCarteGrise;
    }
    
    public void setDateCarteGrise(Date dateCarteGrise) {
        this.dateCarteGrise = dateCarteGrise;
    }
    public Date getDatePu() {
        return this.datePu;
    }
    
    public void setDatePu(Date datePu) {
        this.datePu = datePu;
    }
    public int getReference() {
        return this.reference;
    }
    
    public void setReference(int reference) {
        this.reference = reference;
    }
    public Set getCycloFacteurs() {
        return this.cycloFacteurs;
    }
    
    public void setCycloFacteurs(Set cycloFacteurs) {
        this.cycloFacteurs = cycloFacteurs;
    }
    public Set getCycloBenificiaires() {
        return this.cycloBenificiaires;
    }
    
    public void setCycloBenificiaires(Set cycloBenificiaires) {
        this.cycloBenificiaires = cycloBenificiaires;
    }




}


