package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Drap generated by hbm2java
 */
public class Drap  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Set regions = new HashSet(0);

    public Drap() {
    }

	
    public Drap(String nom) {
        this.nom = nom;
    }
    public Drap(String nom, Set regions) {
       this.nom = nom;
       this.regions = regions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getRegions() {
        return this.regions;
    }
    
    public void setRegions(Set regions) {
        this.regions = regions;
    }




}


