package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Etat generated by hbm2java
 */
public class Etat  implements java.io.Serializable {


     private Integer id;
     private String libelle;
     private Set boiteEtats = new HashSet(0);

    public Etat() {
    }

	
    public Etat(String libelle) {
        this.libelle = libelle;
    }
    public Etat(String libelle, Set boiteEtats) {
       this.libelle = libelle;
       this.boiteEtats = boiteEtats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Set getBoiteEtats() {
        return this.boiteEtats;
    }
    
    public void setBoiteEtats(Set boiteEtats) {
        this.boiteEtats = boiteEtats;
    }




}


