package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facteur generated by hbm2java
 */
public class Facteur  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private int matricule;
     private String prenom;
     private Set cycloFacteurs = new HashSet(0);

    public Facteur() {
    }

	
    public Facteur(String nom, int matricule, String prenom) {
        this.nom = nom;
        this.matricule = matricule;
        this.prenom = prenom;
    }
    public Facteur(String nom, int matricule, String prenom, Set cycloFacteurs) {
       this.nom = nom;
       this.matricule = matricule;
       this.prenom = prenom;
       this.cycloFacteurs = cycloFacteurs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public int getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(int matricule) {
        this.matricule = matricule;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Set getCycloFacteurs() {
        return this.cycloFacteurs;
    }
    
    public void setCycloFacteurs(Set cycloFacteurs) {
        this.cycloFacteurs = cycloFacteurs;
    }




}


