package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1



/**
 * Quartier generated by hbm2java
 */
public class Quartier  implements java.io.Serializable {


     private Integer id;
     private Ville ville;
     private String nom;

    public Quartier() {
    }

    public Quartier(Ville ville, String nom) {
       this.ville = ville;
       this.nom = nom;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ville getVille() {
        return this.ville;
    }
    
    public void setVille(Ville ville) {
        this.ville = ville;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


