package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private Integer id;
     private Drap drap;
     private String nom;
     private Set sites = new HashSet(0);

    public Region() {
    }

	
    public Region(Drap drap, String nom) {
        this.drap = drap;
        this.nom = nom;
    }
    public Region(Drap drap, String nom, Set sites) {
       this.drap = drap;
       this.nom = nom;
       this.sites = sites;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Drap getDrap() {
        return this.drap;
    }
    
    public void setDrap(Drap drap) {
        this.drap = drap;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getSites() {
        return this.sites;
    }
    
    public void setSites(Set sites) {
        this.sites = sites;
    }




}


