package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Secteur generated by hbm2java
 */
public class Secteur  implements java.io.Serializable {


     private Integer id;
     private Site site;
     private int cp;
     private Set tournees = new HashSet(0);

    public Secteur() {
    }

	
    public Secteur(Site site, int cp) {
        this.site = site;
        this.cp = cp;
    }
    public Secteur(Site site, int cp, Set tournees) {
       this.site = site;
       this.cp = cp;
       this.tournees = tournees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Site getSite() {
        return this.site;
    }
    
    public void setSite(Site site) {
        this.site = site;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public Set getTournees() {
        return this.tournees;
    }
    
    public void setTournees(Set tournees) {
        this.tournees = tournees;
    }




}


