package model;
// Generated May 25, 2017 6:09:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ville generated by hbm2java
 */
public class Ville  implements java.io.Serializable {


     private Integer id;
     private Site site;
     private int nom;
     private Set quartiers = new HashSet(0);

    public Ville() {
    }

	
    public Ville(Site site, int nom) {
        this.site = site;
        this.nom = nom;
    }
    public Ville(Site site, int nom, Set quartiers) {
       this.site = site;
       this.nom = nom;
       this.quartiers = quartiers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Site getSite() {
        return this.site;
    }
    
    public void setSite(Site site) {
        this.site = site;
    }
    public int getNom() {
        return this.nom;
    }
    
    public void setNom(int nom) {
        this.nom = nom;
    }
    public Set getQuartiers() {
        return this.quartiers;
    }
    
    public void setQuartiers(Set quartiers) {
        this.quartiers = quartiers;
    }




}


